### ISSUE TITLE
Include instructions in readme that users must allow download

### ISSUE THREAD

**Issue by SebastianZimmeck** [alpiazza13/Open-Source-Anti-Virus#20]
Great work! I just downloaded your app and tried it. I will test it some more. I had to allow the download in my browser (Google Chrome). Maybe, include a brief reference in your [readme](https://github.com/alpiazza13/Open-Source-Anti-Virus/blob/master/README.md) to that effect? Otherwise, users may be waiting ...

<img width="712" alt="Screen Shot 2020-05-01 at 7 25 05 PM" src="https://user-images.githubusercontent.com/11034003/80848648-f9055480-8be1-11ea-8e38-62963555cd35.png">

Also, on a side note, you can put packaged releases in the [release section](https://github.com/alpiazza13/Open-Source-Anti-Virus/releases). Maybe, this is 1.0?

**Comment by alpiazza13** [comment]
> Great work! I just downloaded your app and tried it. I will test it some more. I had to allow the download in my browser (Google Chrome). Maybe, include a brief reference in your [readme](https://github.com/alpiazza13/Open-Source-Anti-Virus/blob/master/README.md) to that effect? Otherwise, users may be waiting ...
> 
> <img alt="Screen Shot 2020-05-01 at 7 25 05 PM" width="712" src="https://user-images.githubusercontent.com/11034003/80848648-f9055480-8be1-11ea-8e38-62963555cd35.png">
> 
> Also, on a side note, you can put packaged releases in the [release section](https://github.com/alpiazza13/Open-Source-Anti-Virus/releases). Maybe, this is 1.0?

Thanks for both pieces of advice - we'll do these! And please do let us know how it is when you test it/if you have any other suggestions.
