### ISSUE TITLE
Add open source license

### ISSUE THREAD

**Issue by SebastianZimmeck** [alpiazza13/Open-Source-Anti-Virus#21]
Perhaps add an [open source license](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository) to your repo? If you click `Create new file` here on your repo and type "LICENSE.md" a bunch of licenses will appear. 

MIT or BSD would be good choices if you want to have a very permissive license. If it is important to you that your code is not used in proprietary software, you can select a copyleft license, such as GNU GPL

**Comment by samueljaval** [comment]
Done!
